
#Game settings
[settings]
	#Are tea bushes bonemealable?
	enableBoneMealTeaBush = false
	#Are coffee bushes bonemealable?
	enableBoneMealCoffeeBush = false
	#Chance of generating wild tea bushes. Bigger value = more frequent.
	#Range: 0 ~ 20
	teaBushChance = 10
	#Chance of generating coffee bushes. Bigger value = more frequent.
	#Range: 0 ~ 20
	coffeeBushChance = 10

