#Whether to show particles or not when crouching to grow things
showParticles = true
#whether to enable the whitelist this does not disable the blacklist
useWhiteList = true
#growables to disable crouching on
blacklist = ["minecraft:netherrack", "minecraft:grass_block", "minecraft:warped_nylium", "minecraft:crimson_nylium", "minecraft:tall_grass", "minecraft:grass", "botanypots", "gaiadimension"]
#growables to enable crouching on (only works if 'useWhiteList' is true and will give exclisivity to those growables) 
whitelist = ["#minecraft:saplings"]
#the minimum number of crouches before the bonemeal is applied (bonemeal is applied randomly so this will not be exact)
#Range: > 0
minCrouchesToApplyBonemeal = 5
#The radius of effect in blocks of applying the growth effect. Not recommended to change due to performance.
#Range: 0 ~ 20
effectRadius = 3
#When true only saplings are allowed to grow with twerking
saplingsOnly = false
#The chance of growth effect being applied from sprinting
#Range: 0.0 ~ 1.0
sprintGrowChance = 0.15
#The chance of growth effect being applied from any source
#Range: 0.0 ~ 1.0
crouchGrowChance = 0.5
#Allow the player to Hold crouch and things grow per x ticks
allowHoldCrouchGrowth = false
#the number of ticks between growths whilst holding crouch
#Range: 0 ~ 1000
holdCrouchGrowthAfterTicks = 5

